- name: "Delete MongoDB role {{ mongodb_rbac_role_name }}"
  community.mongodb.mongodb_role:
    name: "{{ mongodb_rbac_role_name }}"
    database: "{{ mongodb_rbac_role_database }}"
    login_host: "127.0.0.1"
    login_port: "{{ mongodb_port }}"
    login_database: admin
    login_user: "{{ mongodb_admin_user }}"
    login_password: "{{ vault_mongodb_admin_password }}"
    state: absent
  vars:
    ansible_python_interpreter: "{{ mongodb_ansible_python }}"
  no_log: true
